[package]
name = "qmk-led-ui"
version = "0.1.0"
authors = ["Max Schumann <mschumann@de-cix.net>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
hidapi = "2.6.3"
